# Generated by Django 3.1.3 on 2022-09-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('followers', models.ManyToManyField(related_name='_user_followers_+', to='graphql_api.User')),
            ],
        ),
    ]
